bcakmakoglu/vue-flow

- examples/Interaction/InteractionExample.vue
- src/additional-components/Background/Background.vue
- src/components/Edges/utils.ts
- src/composables/useVueFlow.ts
- src/env.d.ts
- src/store/store.ts
- src/types/edge.ts
- src/vite-env.d.ts
* improves cleanup of instances
> feat: use a storage class to map flow instances

- CHANGELOG.md
- LICENSE
- docs/components/home/Acknowledgement.vue
- docs/components/home/Basic.vue
- docs/components/home/flows/Intro.vue
- docs/src/.vuepress/components.d.ts
- docs/src/examples/connectionline.md
- docs/src/examples/custom-node.md
- docs/src/examples/dnd.md
- docs/src/examples/edges.md
- docs/src/examples/empty.md
- docs/src/examples/floating-edges.md
- docs/src/examples/hidden.md
- docs/src/examples/index.md
- docs/src/examples/interaction.md
- docs/src/examples/nesting.md
- docs/src/examples/save.md
- docs/src/examples/stress.md
- docs/src/examples/updatable-edge.md
- docs/src/examples/update-node.md
- docs/src/examples/validation.md
- docs/src/guide/index.md
- docs/src/index.md
- package/package.json
- package/src/components/Edges/utils/simple-bezier.ts
Add webkid copyright to license
> chore: update LICENSE

- CHANGELOG.md
- README.md
- docs/components/home/Acknowledgement.vue
- docs/components/home/flows/Additional.vue
- docs/components/home/flows/Basic.vue
- docs/components/home/flows/Intro.vue
- docs/components/home/flows/Nested.vue
- docs/components/home/flows/RGB.vue
- docs/package.json
- docs/src/.vuepress/components.d.ts
- docs/src/.vuepress/head.ts
- docs/src/guide/index.md
- docs/src/index.md
- package/package.json
- package/src/components/Edges/EdgeText.vue
* Move acknowledgement to bottom of page above footer
* Add acknowledgement node that scrolls down
* Reword home page
> fix: remove 'Floo' from EdgeText.vue

- docs/package.json
- e2e/package.json
- examples/package.json
- package/src/additional-components/MiniMap/MiniMap.vue
- package/src/additional-components/MiniMap/MiniMapNode.vue
- package/src/additional-components/index.ts
- package/src/components/Nodes/NodeWrapper.vue
- package/src/types/components.ts
* Add a slot to minimap nodes to allow customizing the node content
* slots receive current node position and dimensions to position elements and selected + dragging params
> feat: MiniMapNode slot

- docs/package.json
- e2e/package.json
- examples/package.json
- package/src/composables/useHandle.ts
- package/src/utils/graph.ts
* Fix edge update causing double connections
* Fix updateEdge utility adding two edges on update
> fix(edges): edge updater

- docs/components/examples/stress/App.vue
- packages/vue-flow/src/additional-components/MiniMap/MiniMap.vue
- packages/vue-flow/src/additional-components/MiniMap/MiniMapNode.ts
- packages/vue-flow/src/components/Nodes/NodeWrapper.vue
- packages/vue-flow/src/types/hooks.ts
* Add `NodeMouseEvent` interface
* Add `EdgeMouseEvent` interface
* Add `connectedEdges` to node mouse events
> feat(nodes): add connected edges to node mouse events 

- examples/src/Overview/Overview.vue
- packages/vue-flow/src/store/actions.ts
- packages/vue-flow/src/types/changes.ts
- packages/vue-flow/src/utils/changes.ts
* Elements are not added directly to state but parsed and emitted through change handler and then inserted to state
* Remove add element cb from apply changes
> refactor(nodes,edges): Implement node/edge add-changes

- packages/vue-flow/src/utils/graph.ts
- Fixed to return Elements after adding a new Edge.
- fix #155
> fix return of add Edge (#155)

- docs/src/.vuepress/config.ts
- docs/src/.vuepress/theme/clientAppEnhance.ts
- docs/src/.vuepress/theme/index.ts
- package.json
- packages/pathfinding-edge/package.json
- packages/resize-rotate-node/package.json
- packages/vue-flow/package.json
- yarn.lock
- Update docs to use new vuepress 2 plugin api
> docs: use new vuepress plugin api 

- examples/nuxt3/.gitignore
- examples/nuxt3/README.md
- examples/nuxt3/app.vue
- examples/nuxt3/components/BasicFlow.vue
- examples/nuxt3/components/initial-elements.js
- examples/nuxt3/nuxt.config.ts
- examples/nuxt3/package.json
- examples/nuxt3/pages/index.vue
- examples/nuxt3/tsconfig.json
- pnpm-lock.yaml
> examples: add nuxt3 example

- packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
- pass edge markers to edge wrapper
- #175
> fix(edges): pass edge markers to wrapper 

- docs/package.json
- docs/src/.vuepress/copy-plugin.ts
- docs/src/.vuepress/theme/index.ts
- docs/tsconfig.json
- docs/typedoc.json
- pnpm-lock.yaml
* create sidebar from typedoc output
* use plugin markdown to generate typedoc as markdown
> docs: integrate TypeDocs into vuepress output

- docs/src/.vuepress/theme/index.ts
- docs/src/guide/components/background.md
- docs/src/guide/components/control-button.md
- docs/src/guide/components/controls.md
- docs/src/guide/components/minimap-node.md
- docs/src/guide/components/minimap.md
- docs/src/guide/composables.md
- docs/src/guide/config.md
- docs/src/guide/edge.md
- docs/src/guide/getting-started.md
- docs/src/guide/node.md
- docs/src/guide/utils/edge.md
- docs/src/guide/utils/instance.md
- docs/src/guide/vue-flow/config.md
- docs/src/guide/vue-flow/slots.md
- docs/src/guide/vue-flow/state.md
- packages/vue-flow/src/additional-components/Controls/Controls.vue
- packages/vue-flow/src/additional-components/index.ts
* depending on props, hide slot as well
* rename `control-fitview` to `control-fit-view`
> refactor(vue-flow,components): hide/show slots in `Controls.vue`

- packages/vue-flow/src/components/Nodes/NodeWrapper.vue
- packages/vue-flow/src/store/actions.ts
- packages/vue-flow/src/utils/graph.ts
- packages/vue-flow/src/utils/node.ts
- Change 1
- Change 2
- ...
- Issue 1
- Issue 2
- ...
- ...
> fix(handles): correctly calculate handle pos by using viewport zoom 

- packages/vue-flow/src/container/SelectionPane/SelectionPane.vue
- Remove child nodes when parent gets removed
> fix(nodes): remove child nodes when parent gets removed 

- packages/vue-flow/src/container/VueFlow/VueFlow.vue
* add define expose to expose vue flow store instance
> feat: expose flow store and element ref 

- packages/vue-flow/src/container/VueFlow/watch.ts
> fix: prevent falsy values from stopping prop watcher 

- packages/vue-flow/src/components/Nodes/NodeWrapper.vue
- Change 1
- Change 2
- ...
- Issue 1
- Issue 2
- ...
- ...
> release: 0.4.32

- packages/vue-flow/src/composables/useDrag.ts
- packages/vue-flow/src/utils/drag.ts
> fix(nodes): align snap grid to 0,0

- packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
- packages/vue-flow/src/store/actions.ts
- packages/vue-flow/src/utils/store.ts
- rerender edges on update
- #295
> fix(edges): edge-renderer to update on edge updates 

- packages/vue-flow/src/store/getters.ts
- use filter fn to remove orphaned edges
- #291
> fix(edges): use filter to remove orphaned edges 

- packages/vue-flow/src/container/NodeRenderer/NodeRenderer.vue
- packages/vue-flow/src/container/Viewport/Viewport.vue
- Change 1
- Change 2
- ...
- Issue 1
- Issue 2
- ...
- ...
> fix(viewpane,nodes): move resize observer to mounted hooks 

- docs/components/examples/validation/App.vue
- examples/vite/src/Validation/ValidationExample.vue
- package.json
- packages/vue-flow/package.json
- packages/vue-flow/src/components/ConnectionLine/ConnectionLine.vue
- packages/vue-flow/src/components/Edges/EdgeText.vue
- packages/vue-flow/src/composables/useHandle.ts
- packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
- packages/vue-flow/src/container/VueFlow/VueFlow.vue
- packages/vue-flow/src/store/actions.ts
- packages/vue-flow/src/store/hooks.ts
- packages/vue-flow/src/store/state.ts
- packages/vue-flow/src/types/handle.ts
- packages/vue-flow/src/types/hooks.ts
- packages/vue-flow/src/types/store.ts
- pnpm-lock.yaml
- Change 1
- Change 2
- ...
- Issue 1
- Issue 2
- ...
- ...
> feat(store): add connection actions to store

- e2e/cypress/component/1-store/edges/addSelectedEdges.cy.ts
- e2e/cypress/component/1-store/edges/removeSelectedEdges.cy.ts
- e2e/cypress/component/1-store/elements/removeSelectedElements.cy.ts
- e2e/cypress/component/1-store/nodes/addSelectedNodes.cy.ts
- e2e/cypress/component/1-store/nodes/removeSelectedNodes.cy.ts
- e2e/cypress/component/2-flow/drag.cy.ts
- e2e/cypress/utils/elements.ts
- packages/vue-flow/src/store/actions.ts
- fix remove action not removing selected state from passed elements
- update tests
> fix(store): remove selected nodes/edges action not properly removing elements

- .github/workflows/build-and-test.yml
- Change 1
- Change 2
- ...
- ...
> chore: update workflow file 

- .changeset/curly-ligers-end.md
- .changeset/twenty-walls-cheer.md
- docs/components/examples/edges/CustomEdge.vue
- docs/components/examples/edges/CustomEdge2.vue
- docs/components/home/edges/Custom.vue
- docs/src/guide/utils/edge.md
- docs/src/guide/utils/instance.md
- examples/vite/src/Edges/CustomEdge.vue
- examples/vite/src/Edges/CustomEdge2.vue
- examples/vite/src/FloatingEdges/FloatingConnectionLine.vue
- examples/vite/src/FloatingEdges/FloatingEdge.vue
- packages/pathfinding-edge/src/arrow/PerfectArrow.vue
- packages/pathfinding-edge/src/edge/PathFindingEdge.vue
- packages/vue-flow/src/components/ConnectionLine/ConnectionLine.vue
- packages/vue-flow/src/components/Edges/BaseEdge.ts
- packages/vue-flow/src/components/Edges/BezierEdge.ts
- packages/vue-flow/src/components/Edges/SimpleBezierEdge.ts
- packages/vue-flow/src/components/Edges/SmoothStepEdge.ts
- packages/vue-flow/src/components/Edges/StraightEdge.ts
- packages/vue-flow/src/components/Edges/utils/bezier.ts
- packages/vue-flow/src/components/Edges/utils/general.ts
- packages/vue-flow/src/components/Edges/utils/index.ts
- packages/vue-flow/src/components/Edges/utils/simple-bezier.ts
- packages/vue-flow/src/components/Edges/utils/smoothstep.ts
- packages/vue-flow/src/components/Edges/utils/straight.ts
- packages/vue-flow/src/index.ts
- packages/vue-flow/src/types/connection.ts
- packages/vue-flow/src/types/edge.ts
- Change 1
- Change 2
- ...
- ...
> refactor(edges)!: simplify edge paths and center calculations 

- docs/package.json
- package.json
- turbo.json
- Change 1
- Change 2
- ...
- ...
> refactor: remove docs from build process and use separate script 

- examples/nuxt3/components/BasicFlow.vue
- examples/quasar/quasar.config.js
- examples/quasar/src/components/BasicFlow.vue
- examples/quasar/src/components/CustomizedFlow.vue
- examples/quasar/tsconfig.json
- pnpm-lock.yaml
- Change 1
- Change 2
- ...
- ...
> examples: update quasar example

- .changeset/serious-turkeys-reflect.md
- packages/core/src/components/Handle/Handle.vue
- packages/core/src/components/Nodes/DefaultNode.ts
- packages/core/src/components/Nodes/InputNode.ts
- packages/core/src/components/Nodes/OutputNode.ts
- packages/core/src/types/handle.ts
- Change 1
- Change 2
- ...
- ...
> fix(nodes): pass connectable to correct prop

- .changeset/quiet-kings-mate.md
- packages/core/src/components/NodesSelection/NodesSelection.vue
- packages/core/src/style.css
- Change 1
- Change 2
- ...
- ...
> fix(nodes): add missing dragging class to node selection rect

- .changeset/tall-pumas-care.md
- e2e/cypress/component/1-store/elements/removeSelectedElements.cy.ts
- packages/core/src/components/UserSelection/UserSelection.vue
- packages/core/src/store/actions.ts
- packages/core/src/types/store.ts
- packages/core/src/utils/changes.ts
- packages/core/src/utils/node.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): elements not correctly unselected

- .changeset/cuddly-pets-look.md
- packages/core/src/composables/useDrag.ts
- Change 1
- Change 2
- ...
- ...
> revert(nodes): add dragging class to node on drag instead of dragstart

- .changeset/friendly-guests-crash.md
- docs/components/home/flows/Basic.vue
- packages/core/src/components/Edges/Wrapper.ts
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
- Change 1
- Change 2
- ...
- ...
> fix(edges): pass edge styles to edge path

- .changeset/itchy-stingrays-rhyme.md
- packages/core/src/components/Edges/EdgeText.vue
- Change 1
- Change 2
- ...
- ...
> fix(edges): edge text not properly calculating dimensions

- .changeset/large-ligers-listen.md
- .changeset/sharp-jobs-live.md
- .changeset/tame-bobcats-battle.md
- packages/core/src/composables/useEdgeHooks.ts
- packages/core/src/composables/useNodeHooks.ts
- packages/core/src/types/edge.ts
- packages/core/src/types/flow.ts
- packages/core/src/types/node.ts
- packages/core/src/utils/graph.ts
- Change 1
- Change 2
- ...
- ...
> refactor(core): add generics to isNode/isEdge fn

- .changeset/twenty-needles-admire.md
- packages/core/src/composables/useDrag.ts
- Change 1
- Change 2
- ...
- ...
> fix(core,nodes): set node dragging on start and end

- .github/workflows/changelog.yml
- Change 1
- Change 2
- ...
- ...
> chore: generate base changelog on push into master

- .changeset/four-llamas-mate.md
- packages/pathfinding-edge/vite.config.ts
- packages/resize-rotate-node/vite.config.ts
> fix: correct filenames for output of pkgs

- .changeset/stupid-bags-dance.md
- packages/core/src/utils/graph.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): use shallowReactive for node/edge data & events 

- .changeset/big-keys-sort.md
- .changeset/few-ducks-march.md
- packages/core/src/components/Handle/Handle.vue
> fix(core,nodes): connectable `single` applying to *all* handles instead on per handle (for default node types)

- .changeset/sweet-hotels-dress.md
- packages/core/src/components/Edges/Wrapper.ts
> fix(core,edges): use all handles when connection mode is Loose

- .changeset/lemon-news-kiss.md
- .changeset/neat-snakes-mix.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/store/actions.ts
- packages/core/src/types/hooks.ts
- packages/core/src/types/store.ts
- packages/core/src/utils/graph.ts
- add intersection utils to help with checking if a node intersects with either other nodes or a given area
> feat(core): add intersection utils

- .changeset/wild-carrots-occur.md
- examples/vite/main.ts
- examples/vite/package.json
- examples/vite/router.ts
- examples/vite/src/Basic/Basic.vue
- examples/vite/src/Screenshot/ScreenshotExample.vue
- examples/vite/vite.config.ts
- packages/core/package.json
- packages/plugins/screenshot/README.md
- packages/plugins/screenshot/package.json
- packages/plugins/screenshot/src/index.ts
- packages/plugins/screenshot/src/screenshot.ts
- packages/plugins/screenshot/src/store.ts
- packages/plugins/screenshot/src/types.ts
- packages/plugins/screenshot/tsconfig.json
- packages/plugins/screenshot/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- adds screenshot and download screenshot functionality to store
> feat(plugins): add screenshot plugin 

- .changeset/weak-swans-glow.md
- packages/additional-components/package.json
- packages/additional-components/src/minimap/MiniMap.vue
- packages/additional-components/src/minimap/MiniMapNode.ts
- packages/additional-components/src/minimap/types.ts
- packages/core/src/container/Viewport/Viewport.vue
- pnpm-lock.yaml
- Change 1
- Change 2
- ...
- ...
> feat(additional-components): interactive minimap

- .changeset/tender-donkeys-hug.md
- e2e/package.json
- packages/additional-components/package.json
- packages/additional-components/src/auto-imports.d.ts
- packages/additional-components/src/controls/Controls.vue
- packages/vue-flow/README.md
- pnpm-lock.yaml
- Change 1
- Change 2
- ...
- ...
> chore(additional-components): upgrade to vite 3

- .github/workflows/build-and-test.yml
- Change 1
- Change 2
- ...
- ...
> feat: setup turbo cache in gh action

- .changeset/old-dragons-bake.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- Change 1
- Change 2
- ...
- ...
> fix(core,nodes): use node name as class name

- packages/core/src/composables/useDrag.ts
- packages/core/src/composables/useEdge.ts
- packages/core/src/composables/useHandle.ts
- packages/core/src/composables/useNode.ts
- packages/core/src/composables/useVueFlow.ts
- packages/core/src/composables/useZoomPanHelper.ts
- packages/core/src/store/actions.ts
- packages/core/src/utils/graph.ts
- Change 1
- Change 2
- ...
- ...
> chore(core): remove unnecessary imports

- .changeset/tiny-teachers-play.md
- docs/components/examples/index.ts
- docs/components/examples/snap-to-handle/App.vue
- docs/components/examples/snap-to-handle/SnappableConnectionLine.vue
- docs/components/examples/snap-to-handle/index.ts
- docs/src/.vitepress/config.ts
- docs/src/components.d.ts
- docs/src/examples/edges/snap-to-handle.md
- examples/vite/router.ts
- examples/vite/src/SnapHandle/SnapHandleExample.vue
- examples/vite/src/SnapHandle/SnappableConnectionLine.vue
- packages/core/src/index.ts
- New example showing how to snap to closest handles for easy connecting
> docs: snappable connection line example

- docs/components/examples/dnd/App.vue
- Change 1
- Change 2
- ...
- ...
> chore(docs): center dnd nodes after drop

- docs/package.json
- docs/src/.vitepress/config.ts
- docs/src/.vitepress/plugins/vercel-web-vitals-api.ts
- docs/src/.vitepress/theme/index.ts
- docs/src/custom.d.ts
- pnpm-lock.yaml
- Change 1
- Change 2
- ...
- ...
> docs: add vercel analytics

- .changeset/forty-toes-flow.md
- packages/core/src/utils/graph.ts
- Change 1
- Change 2
- ...
- ...
> fix(core,nodes): elevate child nodes by zIndex +1

- .changeset/lovely-flies-jump.md
- packages/core/src/components/Nodes/NodeWrapper.vue
> fix(core,nodes): update position on dimensions change

- .changeset/nine-peas-live.md
- packages/core/src/composables/useEdgeHooks.ts
- packages/core/src/composables/useNodeHooks.ts
- Change 1
- Change 2
- ...
- ...
> fix(core,nodes,edges): nullish check for event obj

- .changeset/spicy-dancers-hug.md
- packages/core/src/utils/watch.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): check for arr length before triggering immediate model watcher

- .changeset/thin-forks-serve.md
- packages/core/src/composables/useKeyPress.ts
- packages/core/src/types/flow.ts
- packages/core/src/types/store.ts
> fix(core): allow null as key-code

- .changeset/young-icons-drive.md
- packages/additional-components/src/minimap/MiniMapNode.ts
> fix(additional-components): render minimap node slot

- .changeset/poor-bottles-rule.md
- packages/core/src/types/handle.ts
- Change 1
- Change 2
- ...
- ...
> refactor(core): add HandleConnectableFunc type

- .changeset/pink-walls-change.md
- packages/core/src/container/Viewport/Viewport.vue
- Change 1
- Change 2
- ...
- ...
> fix(core): allow middle mouse pan over edges

- packages/core/package.json
- packages/core/src/components/Edges/SmoothStepEdge.ts
- packages/core/src/types/edge.ts
- packages/core/vite.config.ts
- pnpm-lock.yaml
- Change 1
- Change 2
- ...
- ...
> chore(deps-dev,core): add extended vue macros

- .changeset/tasty-insects-grin.md
- packages/core/src/auto-imports.d.ts
- packages/core/src/composables/useDrag.ts
- packages/core/src/utils/drag.ts
> refactor(nodes): only trigger dragging flag when a change has occured

- .changeset/fuzzy-books-beg.md
- packages/additional-components/src/minimap/MiniMap.vue
- packages/core/src/container/Viewport/Viewport.vue
> fix(core,additional-components): apply translate extent on pan

- .changeset/giant-shirts-carry.md
- packages/core/src/utils/drag.ts
> fix(nodes): properly calculate node extent

- .changeset/blue-ghosts-do.md
- packages/core/src/store/state.ts
- packages/core/src/utils/store.ts
- packages/core/src/utils/watch.ts
- Change 1
- Change 2
- ...
- ...
> refactor(core): separate model and store watchers

- .changeset/gorgeous-hairs-obey.md
- packages/core/src/utils/watch.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): watcher not working with onMounted hook

- .changeset/quiet-plants-mate.md
- packages/core/src/utils/drag.ts
> fix(core): node extent not properly applied for child nodes

- .github/workflows/publish.yml
> refactor: use `next release` as release commit message

- .changeset/stupid-moons-push.md
- packages/core/src/utils/watch.ts
> fix(core): prevent watcher being stopped oncleanup

- .changeset/beige-swans-hear.md
- .changeset/neat-oranges-nail.md
- packages/additional-components/src/minimap/MiniMap.vue
- packages/additional-components/src/minimap/MiniMapNode.ts
- packages/core/src/types/node.ts
- Change 1
- Change 2
- ...
- ...
> fix(minimap): add missing dragging and selected flags to minimap node slots

- .changeset/silly-experts-crash.md
- packages/core/src/composables/useGetPointerPosition.ts
- Change 1
- Change 2
- ...
- ...
> chore(core): remove log

- .changeset/fast-horses-give.md
- .changeset/selfish-trains-perform.md
- packages/core/src/components/Handle/Handle.vue
- packages/core/src/store/actions.ts
- packages/core/src/types/node.ts
- packages/core/src/utils/graph.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): add initialized prop to GraphNode

- docs/src/.vitepress/config.ts
- docs/src/guide/components/background.md
- docs/src/guide/components/controls.md
- docs/src/guide/components/minimap.md
- docs/src/migration/index.md
- packages/background/README.md
- packages/controls/README.md
- packages/minimap/README.md
- Change 1
- Change 2
- ...
- ...
> docs: update component documentation with new examples

- .changeset/great-gorillas-ring.md
- packages/core/src/utils/watch.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): element watcher not emitting changes with `addNodes` / `addEdges`

- .changeset/long-pillows-brush.md
- packages/core/src/container/NodeRenderer/NodeRenderer.vue
- Change 1
- Change 2
- ...
- ...
> refactor(core,nodes): remove forced update on resize observer trigger

- .changeset/nasty-trees-guess.md
- packages/core/src/utils/node.ts
- Change 1
- Change 2
- ...
- ...
> refactor(core): use vue-flow__handle in handle bounds selector

- .changeset/cyan-tips-add.md
- .changeset/funny-falcons-doubt.md
- examples/vite/src/Edges/CustomEdge2.vue
- packages/core/src/components/Edges/BaseEdge.ts
- packages/core/src/components/Edges/BezierEdge.ts
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/components/Edges/SimpleBezierEdge.ts
- packages/core/src/components/Edges/SmoothStepEdge.ts
- packages/core/src/components/Edges/StepEdge.ts
- packages/core/src/components/Edges/StraightEdge.ts
- packages/core/src/types/edge.ts
- Change 1
- Change 2
- ...
- ...
> feat(edges): forward edge class to custom edges

- .changeset/gentle-deers-brush.md
- packages/core/src/utils/watch.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): overwrite state even if it's an empty arr

- .changeset/green-llamas-punch.md
- packages/core/src/container/NodeRenderer/NodeRenderer.vue
- packages/core/src/store/actions.ts
> revert(core): force update on resize observer changes

- .changeset/old-readers-try.md
- packages/core/src/utils/watch.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): move watcher timing to pre and sync immediately

- .changeset/angry-bats-explain.md
- packages/core/src/components/Edges/BaseEdge.ts
- packages/core/src/types/edge.ts
- Change 1
- Change 2
- ...
- ...
> refactor(core,edges): make label coords optional

- .changeset/quick-jars-fold.md
- packages/core/src/composables/useKeyPress.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): input focus preventing selection rect / multi-select

- .changeset/shy-flowers-live.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/container/VueFlow/VueFlow.vue
- packages/core/src/store/state.ts
- packages/core/src/types/flow.ts
- packages/core/src/types/store.ts
- Change 1
- Change 2
- ...
- ...
> feat(core,nodes): add elevateNodesOnSelect option

- .changeset/tidy-rocks-occur.md
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
- Change 1
- Change 2
- ...
- ...
> refactor(core,edges): group edges on edge selection changes

- .changeset/five-hornets-look.md
- packages/core/src/utils/changes.ts
- Change 1
- Change 2
- ...
- ...
> fix(core): prevent expandParent from moving parent node while expanding

- .changeset/chatty-ducks-fetch.md
- examples/vite/src/Basic/Basic.vue
- examples/vite/src/Basic/BasicOptionsAPI.vue
- examples/vite/src/CustomNode/CustomNode.vue
- examples/vite/src/DragNDrop/DnD.vue
- packages/core/src/utils/graph.ts
> chore(core): deprecate options api utils

- .github/workflows/build-and-test.yml
- Change 1
- Change 2
- ...
- ...
> refactor(workflows): use node 18

- .github/workflows/build-and-test.yml
- Change 1
- Change 2
- ...
- ...
> refactor(workflows): use frozen lockfile

- .changeset/serious-mugs-relax.md
- .changeset/strong-stingrays-scream.md
- packages/background/src/Background.vue
- packages/node-toolbar/src/NodeToolbar.vue
- Change 1
- Change 2
- ...
- ...
> fix(background): set container styles for bg

- .github/workflows/build-and-test.yml
- Cancel previous workflow runs if newer one is triggered
> feat(workflows): add concurrency

- docs/components/DocsRepl.vue
- docs/components/Repl.vue
- docs/package.json
- pnpm-lock.yaml
> docs: suspend Repl

- .changeset/large-actors-tap.md
- .changeset/sixty-lions-tell.md
- .github/workflows/build-and-test.yml
- .github/workflows/publish.yml
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
- packages/core/src/container/NodeRenderer/NodeRenderer.vue
- packages/core/src/types/connection.ts
- Only check if slot exists by checking slot object names
- Remove `nodes` from `ConnectionLineProps`
> fix(core,nodes): slot props undefined on first render

- .changeset/eight-donuts-exercise.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/utils/changes.ts
> refactor(core): allow omitting width/height styles for parent nodes

- .changeset/bright-timers-itch.md
- packages/core/package.json
- packages/core/src/types/node.ts
- packages/core/src/utils/drag.ts
> feat(core): allow setting padding for extent parent

- .changeset/hot-bobcats-jump.md
- examples/vite/src/Nesting/Nesting.vue
- packages/core/src/components/Nodes/NodeWrapper.vue
> fix(core): reapply node extent on change

- .changeset/curly-vans-crash.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/composables/useDrag.ts
- packages/core/src/composables/useUpdateNodePositions.ts
- packages/core/src/utils/drag.ts
> fix(core): calculate position and computedPos correctly in `calcNextPosition`

- .changeset/brown-yaks-sin.md
- packages/core/src/utils/changes.ts
> refactor(core): check if element still exists before attempting removal

- .changeset/dirty-turkeys-thank.md
- packages/core/.eslintrc.js
- packages/core/patch/slots.js
- packages/core/src/utils/changes.ts
> fix(core): prevent unselectable elements from being selected

- .github/workflows/build-and-test.yml
- .github/workflows/publish.yml
> refactor(workflows): update cache key for turborepo

- .changeset/spotty-mugs-tell.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/composables/useKeyPress.ts
> fix(core): bubble up keydown event in node wrapper

- .changeset/eight-readers-own.md
- packages/core/src/container/Viewport/Viewport.vue
> fix(core): place default slot outside of viewport el

- .changeset/stale-bats-agree.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
> fix(core): check if position is a number and not if it's truthy

- .changeset/smart-news-study.md
- packages/core/src/composables/useKeyPress.ts
> fix(core): always handle keyup

- .changeset/fast-fireants-reflect.md
- packages/core/src/composables/useKeyPress.ts
> refactor(core): support key combinations for key codes

- .changeset/kind-carrots-hang.md
- packages/core/src/container/Pane/Pane.vue
> refactor(core): keep user selection on right click

- .github/workflows/build-and-test.yml
- docs/package.json
- pnpm-lock.yaml
> refactor(workflows): use cypress action

- .changeset/famous-jars-tie.md
- packages/core/src/components/Nodes/NodeWrapper.vue
> fix(core): add timeout when updating positions after extent changes

- .changeset/angry-roses-exercise.md
- packages/core/src/utils/changes.ts
> refactor(core): add warning if trying to duplicate an element

- .changeset/clever-ties-dance.md
- .changeset/gold-rocks-thank.md
- examples/vite/src/SaveRestore/Controls.vue
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/composables/useDrag.ts
- packages/core/src/composables/useVueFlow.ts
- packages/core/src/store/actions.ts
- packages/core/src/types/store.ts
- packages/core/src/utils/changes.ts
- packages/core/src/utils/graph.ts
- packages/core/src/utils/node.ts
- packages/core/src/utils/store.ts
- packages/core/src/utils/watch.ts
> fix(core): use computed var to get current node in drag handler

- .changeset/silent-garlics-pay.md
- packages/core/src/container/Pane/Pane.vue
> fix(core): hide node selection if no selected nodes exist

- package.json
- pnpm-lock.yaml
> chore(deps-dev): update deps-dev

- .changeset/eleven-monkeys-glow.md
- packages/core/src/index.ts
> feat(core): export getSimpleEdgeCenter & getBezierEdgeCenter

- .changeset/tame-bugs-clean.md
- packages/core/src/index.ts
- packages/core/src/types/flow.ts
- packages/core/src/utils/graph.ts
> feat(core): export isGraphNode & isGraphEdge typeguards

- .changeset/fifty-jobs-train.md
- .changeset/tall-lizards-care.md
- packages/core/src/auto-imports.d.ts
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/composables/useDrag.ts
- packages/core/src/composables/useGetPointerPosition.ts
- packages/core/src/composables/useHandle.ts
- packages/core/src/container/Viewport/Viewport.vue
- packages/core/src/container/VueFlow/VueFlow.vue
- packages/core/src/store/actions.ts
- packages/core/src/store/state.ts
- packages/core/src/style.css
- packages/core/src/types/flow.ts
- packages/core/src/types/store.ts
- packages/core/src/utils/autopan.ts
- packages/core/src/utils/drag.ts
- packages/core/src/utils/general.ts
- Add options to auto-pan viewport when dragging node / connection line
> feat(core): add auto pan props

- .changeset/brave-carrots-draw.md
- packages/core/src/types/edge.ts
- packages/core/src/types/node.ts
> feat(core): allow setting node/edge type with generic

- .changeset/spotty-gorillas-wash.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/utils/handle.ts
> fix(core): pass valid connection func params

- .changeset/pretty-ducks-shop.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/store/actions.ts
> fix(core): ref access when passing default edge options

- .changeset/fair-snakes-jam.md
- packages/node-resizer/src/NodeResizer.vue
- packages/node-resizer/src/ResizeControl.vue
- packages/node-resizer/src/ResizeControlLine.vue
- packages/node-resizer/src/types.ts
- packages/node-resizer/src/utils.ts
> feat(node-resizer): add shouldResize option

- .changeset/new-falcons-approve.md
- .changeset/shaggy-dots-wait.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/utils/handle.ts
> fix(core): ios connection error

- .changeset/plenty-maps-shout.md
- packages/core/src/composables/useDrag.ts
- packages/core/src/composables/useUpdateNodePositions.ts
- packages/core/src/utils/drag.ts
> fix(core): avoid undraggable selected nodes being dragged

- .github/ISSUE_TEMPLATE/config.yml
> chore: correct links in issue template

- .changeset/tidy-laws-begin.md
- packages/core/src/auto-imports.d.ts
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
- packages/core/src/composables/useHandle.ts
- packages/core/src/store/state.ts
- packages/core/src/types/connection.ts
- packages/core/src/types/store.ts
- packages/core/src/utils/handle.ts
> feat(core): add connection status to connection lines

- .changeset/ninety-cooks-report.md
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
> refactor(core): use opposite position for connection lines

- .changeset/spotty-chairs-allow.md
- packages/core/src/auto-imports.d.ts
- packages/core/src/composables/useEdge.ts
- packages/core/src/composables/useNode.ts
- packages/core/src/composables/useVueFlow.ts
- packages/core/src/index.ts
- packages/core/src/utils/log.ts
> feat(core): add vue flow error class

- .changeset/green-bats-reply.md
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
- packages/core/src/composables/useHandle.ts
> fix(core): check if prevClosestHandle exists in pointer up

- .changeset/sixty-buses-share.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/store/actions.ts
- packages/core/src/types/store.ts
> refactor(core): cleanup useHandle and set status on actions

- .changeset/nine-geckos-rest.md
- docs/components/examples/basic/App.vue
- docs/components/examples/custom-node/App.vue
- docs/components/examples/horizontal/App.vue
- docs/components/examples/intersection/App.vue
- docs/src/components.d.ts
- packages/core/src/container/Viewport/Viewport.vue
- packages/pathfinding-edge/example/App.vue
- packages/pathfinding-edge/example/elements.ts
> chore(docs): replace `default-zoom` with `defaut-viewport`

- packages/core/src/components/Edges/EdgeText.vue
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/components/Panel/Panel.vue
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
- packages/core/src/container/NodeRenderer/NodeRenderer.vue
- packages/core/src/container/Viewport/Viewport.vue
- packages/core/src/utils/autopan.ts
- packages/core/src/utils/changes.ts
- packages/core/src/utils/drag.ts
- packages/core/src/utils/edge.ts
- packages/core/src/utils/general.ts
- packages/core/src/utils/graph.ts
- packages/core/src/utils/log.ts
- packages/core/src/utils/node.ts
- packages/core/src/utils/store.ts
- packages/core/src/utils/watch.ts
> chore(core): cleanup and replace `const` with `function`

- packages/node-resizer/src/ResizeControl.vue
> refactor(node-resizer): apply min width and height with aspect ratio

- .github/workflows/build-and-test.yml
- .github/workflows/qodana.yml
- qodana.yaml
> feat(workflows): add qodana scan

- examples/vite/src/CustomNode/CustomNode.vue
- examples/vite/src/NodeTypeChange/NodeTypeChangeExample.vue
- examples/vite/src/Overview/Overview.vue
- examples/vite/src/Unidirectional/UnidirectionalExample.vue
- examples/vite/src/UpdatableEdge/UpdatableEdgeExample.vue
- packages/core/src/components/Edges/utils/smoothstep.ts
- packages/core/src/container/VueFlow/VueFlow.vue
> examples: cleanup examples and remove deprecated usages

- .changeset/wild-waves-pump.md
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
> fix(core): prevent rendering edges that have been removed

- packages/core/src/store/actions.ts
> chore(core): remove any typecast

- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/container/NodeRenderer/NodeRenderer.vue
> refactor(core): use watcheffect to observe node dimensions

- .changeset/nine-beers-admire.md
- .changeset/popular-coats-burn.md
- .changeset/spotty-boxes-boil.md
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
- packages/core/src/store/state.ts
- packages/core/src/types/flow.ts
- packages/core/src/types/store.ts
> fix(core): allow null for deprecated connection line type

- .changeset/rotten-horses-fetch.md
- .changeset/six-bugs-crash.md
- examples/vite/src/Basic/Basic.vue
- examples/vite/src/CustomConnectionLine/CustomConnectionLine.vue
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/composables/useHandle.ts
- packages/core/src/types/hooks.ts
> refactor(core,types): use MouseTouchEvent for EdgeMouseEvent type

- .changeset/ninety-crabs-shout.md
- .changeset/polite-oranges-retire.md
- packages/core/src/auto-imports.d.ts
- packages/core/src/composables/useViewport.ts
- packages/core/src/composables/useZoomPanHelper.ts
- packages/core/src/container/Viewport/Transform.vue
- packages/core/src/container/Viewport/Viewport.vue
- packages/core/src/store/actions.ts
- packages/core/src/types/store.ts
- tests/cypress/component/1-store/viewpane/setMaxZoom.cy.ts
- tests/cypress/component/1-store/viewpane/setMinZoom.cy.ts
> fix(core): hide graph until nodes are ready

- .changeset/witty-humans-fold.md
- packages/core/src/components/Nodes/NodeWrapper.vue
> refactor(core): use snap grid to clamp initial node pos

- .changeset/lucky-cups-bake.md
- packages/core/src/store/actions.ts
- packages/core/src/types/flow.ts
> refactor(core): omit internal properties when using toObject

- .changeset/dry-bees-impress.md
- packages/core/src/components/Nodes/NodeWrapper.vue
> fix(core): cast zIndex to number in node wrapper

- .changeset/cyan-melons-unite.md
- packages/core/src/store/actions.ts
- packages/core/src/store/state.ts
- packages/core/src/types/flow.ts
- Change 1
- Change 2
- ...
- ...
> refactor(core)!: remove experimental features flag

- .changeset/young-glasses-swim.md
- packages/core/src/store/actions.ts
> fix(core): compare internal node dimensions when updating

- .changeset/four-years-serve.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/utils/handle.ts
> fix(core): check if handle is connectable

- .changeset/pink-ducks-switch.md
- packages/core/src/components/Nodes/NodeWrapper.vue
- packages/core/src/composables/useDrag.ts
- packages/core/src/utils/node.ts
> fix(core): blur node after unselect

- .changeset/giant-bags-hug.md
- packages/core/src/components/ConnectionLine/ConnectionLine.vue
- packages/core/src/composables/useHandle.ts
- packages/core/src/store/actions.ts
- packages/core/src/types/connection.ts
- packages/core/src/types/handle.ts
- packages/core/src/types/store.ts
- packages/core/src/utils/handle.ts
- tests/cypress/component/2-vue-flow/connect.cy.ts
- tests/cypress/component/2-vue-flow/customConnectionLine.cy.ts
- tests/cypress/support/component.ts
> feat(core): store handle validation in store state

- .changeset/clever-crabs-shop.md
- .changeset/shiny-boxes-prove.md
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/composables/useHandle.ts
- packages/core/src/container/VueFlow/VueFlow.vue
- packages/core/src/store/actions.ts
- packages/core/src/store/state.ts
- packages/core/src/types/flow.ts
- packages/core/src/types/store.ts
- tests/cypress/component/2-vue-flow/connect.cy.ts
- tests/cypress/component/2-vue-flow/isValidConnection.cy.ts
- tests/cypress/component/2-vue-flow/updateEdge.cy.ts
- tests/cypress/support/component.ts
> feat(core): add isValidConnection prop

- .changeset/gold-bugs-protect.md
- packages/core/src/composables/useHandle.ts
- packages/minimap/src/MiniMapNode.ts
> fix(core): check if valid connection func exists

- .changeset/ninety-crews-remember.md
- .changeset/twelve-seahorses-play.md
- packages/core/src/components/Nodes/NodeWrapper.ts
- packages/core/src/types/node.ts
> fix(core,nodes): unwrap refs and pass props

- .changeset/fluffy-pans-boil.md
- packages/core/src/composables/useEdge.ts
- packages/core/src/composables/useNode.ts
- packages/core/src/store/actions.ts
- packages/core/src/types/store.ts
> refactor(core)!: GraphNode, GraphEdge as generic for findNode, `findEdge` actions

- .changeset/thirty-lions-tickle.md
- packages/core/src/container/Viewport/Viewport.vue
> fix(core): non-passive wheel event listener violation

- .changeset/long-trains-allow.md
- .changeset/slow-roses-buy.md
- .changeset/wicked-falcons-unite.md
- packages/background/src/Background.vue
- packages/background/src/patterns.ts
- packages/background/src/types.ts
> feat(background): add offset prop

- .changeset/giant-feet-sing.md
- packages/core/src/utils/graph.ts
> feat(core): allow passing object with only id to getConnectedEdges

- .changeset/smooth-dancers-collect.md
- packages/core/src/container/NodeRenderer/NodeRenderer.vue
> fix(core): only use visible nodes to check if nodes are initialized

- .changeset/green-adults-design.md
- packages/core/src/container/VueFlow/VueFlow.vue
> fix(core): add missing error event definition

- .changeset/mean-fireants-hope.md
- packages/core/src/theme-default.css
> fix(core): use default color as fallback for css vars

- .changeset/giant-gifts-retire.md
- examples/vite/src/NodeResizer/NodeResizerExample.vue
- examples/vite/src/NodeResizer/ResizableNodeSelected.vue
- packages/node-resizer/src/NodeResizer.vue
> fix(node-resizer): hide resizer when isVisible is false

- packages/controls/src/style.css
- remove the boder of controls
> fix(controls): remove border, make the control look modern

- .changeset/old-ways-laugh.md
- packages/core/src/utils/drag.ts
> fix(core): check if node exists during drag

- .changeset/tough-mangos-mix.md
- packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
> fix(core): orphaned edge warn for undeletable edges when calculating max z-index

- .changeset/spicy-crabs-hide.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/utils/handle.ts
> fix(core): use all handles in radius and find closest valid one

- .changeset/late-cherries-laugh.md
- packages/core/src/components/Edges/BaseEdge.ts
- packages/core/src/style.css
> fix(core): set interaction edge styles so animation does not break pointer

- .changeset/honest-terms-travel.md
- packages/node-resizer/src/NodeResizer.vue
- packages/node-resizer/src/ResizeControl.vue
- packages/node-resizer/src/types.ts
> fix(node-resizer): enforce min/max width/height on nodes

- .changeset/wise-apes-enjoy.md
- packages/core/src/store/actions.ts
- packages/core/src/types/store.ts
- Return Promise from `fromObject` action
> refactor(core): return promise from fromObject

- .changeset/swift-rockets-trade.md
- packages/core/src/composables/useConnection.ts
- add `useConnection` composable for easy access of current connection params
> feat(core): add useConnection composable

- .changeset/lazy-cherries-sparkle.md
- packages/minimap/src/MiniMap.vue
- inherit attrs again in minimap cmp
> revert(minimap): inherit attrs

- .changeset/grumpy-elephants-burn.md
- .changeset/smooth-steaks-doubt.md
- .changeset/warm-spiders-drum.md
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/components/Nodes/NodeWrapper.ts
- packages/core/src/composables/useKeyPress.ts
- packages/core/src/container/Viewport/Viewport.vue
- packages/core/src/env.d.ts
- packages/core/src/store/actions.ts
- packages/core/src/store/state.ts
- packages/core/src/types/components.ts
- packages/core/src/types/edge.ts
- packages/core/src/types/hooks.ts
- packages/core/src/types/node.ts
- packages/core/src/utils/graph.ts
- packages/core/src/utils/handle.ts
- pnpm-lock.yaml
- tooling/eslint-config/index.js
- tooling/eslint-config/package.json
- Return false from `currentKeyFilter` if the `keyFilter` is a boolean value to not trigger the actual key handler and overwrite `isPressed`
- Set `isPressed` to whatever `keyFilter` is if it's a boolean
- Allow panning on scroll when selection is active
> fix(core,viewport): allow panning on scroll while selection is active

- .changeset/large-lemons-end.md
- .changeset/many-actors-talk.md
- .changeset/two-roses-shake.md
- docs/components/DocsRepl.vue
- docs/components/home/flows/Intro.vue
- packages/core/src/composables/useViewport.ts
- packages/core/src/container/Viewport/Transform.vue
- packages/core/src/container/Viewport/Viewport.vue
- packages/core/src/store/actions.ts
- packages/core/src/store/state.ts
- packages/core/src/types/store.ts
- Add `fitViewOnInitDone` to state
- Emit pane ready after timeout of 1ms
- Suspend transformation pane until dimensions of viewport are ready
> refactor(core): add fitViewOnInitDone to state

- .changeset/spicy-donkeys-drum.md
- packages/controls/src/style.css
- set full width on control button svg elements
> fix(controls): set full width on control btn svgs 

- .changeset/chilly-cameras-promise.md
- packages/core/src/composables/useNode.ts
- packages/core/src/composables/useNodeId.ts
- add `useNodeId` composable
```ts
// CustomNode.vue
const nodeId = useNodeId() // '1'
> feat(core): add `useNodeId` composable

- .changeset/sweet-cameras-decide.md
- packages/core/src/composables/useVueFlow.ts
- packages/core/src/composables/useWatchProps.ts
- packages/core/src/container/EdgeRenderer/MarkerDefinitions.vue
- packages/core/src/store/actions.ts
- packages/core/src/store/getters.ts
- packages/core/src/store/state.ts
- packages/core/src/utils/changes.ts
- packages/core/src/utils/graph.ts
- packages/core/src/utils/handle.ts
- Replace `forEach` loops with `for...of`
> perf(core): replace Array.forEach loops

- packages/core/src/components/Edges/utils/bezier.ts
- packages/core/src/components/Edges/utils/simple-bezier.ts
- packages/core/src/components/Edges/utils/smoothstep.ts
- packages/core/src/index.ts
- packages/core/src/store/getters.ts
- packages/core/src/store/state.ts
- packages/core/src/utils/changes.ts
- packages/core/src/utils/defaultNodesEdges.ts
- Remove exports from barrel files
> refactor(core): remove exports from barrel files

- .changeset/tall-avocados-type.md
- packages/core/src/utils/store.ts
- Add `edgeId` to return value of `useHandleConnections`
> feat(core,composables): add edgeId to useHandleConnections return

- .changeset/nasty-turtles-hear.md
- packages/core/src/components/Edges/utils/bezier.ts
- packages/core/src/components/Edges/utils/smoothstep.ts
> fix(core,edges): correct smoothstep edge pathing

- .changeset/four-tips-stare.md
- packages/core/src/composables/useNodesData.ts
> fix(core,composables): correct typing of useNodesData return

- .changeset/tasty-maps-return.md
- packages/core/src/components/NodesSelection/NodesSelection.vue
- packages/core/src/composables/useVueFlow.ts
- packages/core/src/container/EdgeRenderer/MarkerDefinitions.vue
- packages/core/src/utils/storage.ts
> fix(core): store vf instance on vue app for ssr 

- .github/actions/install-dependencies/action.yaml
- README.md
- docs/examples/index.ts
- docs/examples/layout/useLayout.js
- examples/vite/package.json
- examples/vite/src/Layouting/LayoutingExample.vue
- examples/vite/src/Layouting/useRunProcess.ts
- package.json
- pnpm-lock.yaml
- tooling/eslint-config/package.json
- Replace `dagre` pkg with `@dagrejs/dagre`
- Update pnpm to 9
> chore(docs,examples): replace dagre with dagrejs/dagre

- .changeset/lovely-buttons-tickle.md
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/container/Viewport/Viewport.vue
> chore: next release

- .changeset/breezy-panthers-rescue.md
- packages/core/src/composables/useHandle.ts
> fix(core): prevent auto pan if set to false

- packages/core/src/composables/useUpdateNodePositions.ts
- packages/core/src/composables/useViewportHelper.ts
- packages/core/src/store/actions.ts
- packages/core/src/store/getters.ts
- packages/core/src/utils/changes.ts
- packages/core/src/utils/drag.ts
- packages/core/src/utils/store.ts
- Replace array fns with for loops
> refactor(core): replace array fns

- .changeset/odd-planes-cheat.md
- packages/minimap/src/MiniMap.vue
- packages/minimap/src/types.ts
- Add `maskBorderRadius` prop to minimap
> feat(minimap): add `maskBorderRadius` prop

- .changeset/ninety-olives-dress.md
- packages/core/src/types/flow.ts
- Add event type names to simplify events and avoid hitting complexity limit of TS
> fix(core): simplify event emit definitions to avoid hitting complexity limit of TS

- .changeset/smart-lies-impress.md
- packages/core/src/components/ConnectionLine/index.ts
> fix(core): use all handle bounds in loose connection mode

- docs/examples/index.ts
- docs/examples/layout-simple/App.vue
- docs/examples/layout-simple/Icon.vue
- docs/examples/layout-simple/index.ts
- docs/examples/layout-simple/initial-elements.js
- docs/examples/layout-simple/useLayout.js
- docs/examples/layout/App.vue
- docs/examples/layout/initial-elements.js
- docs/package.json
- docs/src/.vitepress/config.mts
- docs/src/examples/layout/animated.md
- docs/src/examples/layout/simple.md
- pnpm-lock.yaml
> docs(examples): add simple layout example

- .changeset/kind-eels-develop.md
- examples/vite/index.css
- packages/background/src/Background.vue
> fix(background): set default offset to `0`

- .changeset/selfish-falcons-run.md
- packages/core/src/composables/useKeyPress.ts
> fix(core): allow using + as a key in key combinations

- .changeset/tame-cups-tan.md
- packages/core/src/components/Nodes/DefaultNode.ts
- packages/core/src/components/Nodes/InputNode.ts
- packages/core/src/components/Nodes/OutputNode.ts
> fix(core): escape node labels

- docs/src/guide/getting-started.md
> fix(guide): Add missing import

- .changeset/flat-impalas-look.md
- packages/core/src/container/Pane/Pane.vue
- packages/core/src/utils/store.ts
- Use connection lookup to check for elements to select in a user selection box
>  refactor(core): use connection lookup to check for selected elements 

- .changeset/shaggy-penguins-invite.md
- packages/core/src/container/Pane/Pane.vue
> fix(core): prevent pane click event when connection is in progress 

- .changeset/plenty-rocks-impress.md
- packages/core/src/components/Handle/Handle.vue
> fix(core): avoid removing handle bounds on handle unmount

- .changeset/tame-cars-occur.md
- packages/core/src/container/Pane/Pane.vue
> fix(core): unwrap ref when checking if connection in progress

- .changeset/wild-bobcats-wash.md
- packages/core/src/utils/general.ts
- packages/core/src/utils/handle.ts
> fix(core): fall back to changedTouches for touchend events

- .changeset/tender-jobs-search.md
- packages/core/src/components/Edges/EdgeWrapper.ts
- packages/core/src/components/Nodes/NodeWrapper.ts
- packages/core/src/store/state.ts
- packages/core/src/types/edge.ts
- packages/core/src/types/flow.ts
- packages/core/src/types/node.ts
> feat(core): add dom attributes option for nodes and edges

- .changeset/twelve-olives-fly.md
- examples/vite/src/Basic/Basic.vue
- packages/core/src/store/actions.ts
> fix(core): use correct handlesuffix in getHandleConnections 

- docs/examples/helper-lines/App.vue
- docs/examples/helper-lines/HelperLines.vue
- docs/examples/helper-lines/index.ts
- docs/examples/helper-lines/initialElements.ts
- docs/examples/helper-lines/style.css
- docs/examples/helper-lines/utils.ts
- docs/examples/index.ts
- docs/src/.vitepress/config.mts
- docs/src/examples/helper-lines.md
- docs/src/guide/node.md
Add an example of helper lines
*From React Flow transplantation*
Fix type error in vitepress's config.mts file
This PR only updates documentation and does not require a version bump.
> feat: add optional chaining to prevent types errors and add an example of helper lines

- .changeset/perfect-coins-rest.md
- .changeset/quick-dolphins-juggle.md
- examples/vite/src/Basic/CustomNode.vue
- packages/core/src/container/Viewport/Viewport.vue
- packages/core/src/index.ts
- packages/core/src/utils/graph.ts
- packages/minimap/src/MiniMap.vue
- Expose wheelDelta utility fn
- Apply wheelDelta to minimap zoom
> feat(core): expose wheelDelta utility

- .changeset/stale-phones-cross.md
- packages/core/src/utils/handle.ts
> fix(core): fetch correct source and target nodes for isValidConnection

- .changeset/stupid-bags-itch.md
- packages/core/src/composables/useResizeHandler.ts
> fix(core): skip resize handler if node not visible

- .changeset/selfish-geese-attack.md
- packages/core/src/composables/useHandle.ts
- packages/core/src/container/Viewport/Viewport.vue
> fix(core): prevent multi touch from aborting connections

- .changeset/wise-jobs-perform.md
- packages/core/src/components/ConnectionLine/index.ts
> fix(core): unwrap connection line status ref
