bcakmakoglu/vue-flow

docs/components/home/Home.vue
examples/src/Basic/Basic.vue
package/src/components/Edges/BaseEdge.vue
package/src/composables/index.ts
package/src/composables/useZoomPanHelper.ts
package/src/container/Viewport/Transform.vue
package/src/store/getters.ts

* Wait for viewport & nodes to have their dimensions established before emitting paneReady
* Avoids getting 0 values for dimensions on paneReady

fix(viewport): emit paneReady when dimensions are ready

---

package/src/composables/useZoomPanHelper.ts

* Clamp x, y positions before applying transformations so we can't position the d3container outside the permissable translate extent

fix: clamp transforms

---

e2e/cypress/integration/1-store/setState.spec.ts
package/src/components/Edges/EdgeWrapper.vue
package/src/components/Nodes/NodeWrapper.vue
package/src/container/EdgeRenderer/EdgeRenderer.vue
package/src/container/NodeRenderer/NodeRenderer.vue
package/src/store/actions.ts
package/src/store/getters.ts
package/src/types/edge.ts
package/src/utils/changes.ts
package/src/utils/edge.ts

* Remove source/targetNode properties from GraphEdge type (still passed to custom edges)
* Remove edges when they have no existing source or target nodes that can be found in the state
* Add nodes to custom edge test

fix(edges): Remove orphaned edges

---

package/src/composables/useKeyPress.ts
package/src/container/SelectionPane/SelectionPane.vue
package/src/container/Viewport/Viewport.vue

* Use ref for keycodes from store to reactively listen to keyboard events and trigger delete etc.

fix: Reactive key bindings for delete, select etc.

---

package/src/container/VueFlow/VueFlow.vue
package/src/container/VueFlow/watch.ts
package/src/store/state.ts

* Set props on watcher initialization, so we avoid duplicate setStates (from composable and watchers)
* Fix pausable watchers not starting up
* Flush watchers on post

fix: duplicate setState on vue flow mount

---

package/src/composables/useVueFlow.ts
package/src/container/EdgeRenderer/EdgeRenderer.vue
package/src/types/changes.ts
package/src/types/connection.ts
package/src/types/edge.ts
package/src/types/flow.ts
package/src/types/hooks.ts
package/src/types/node.ts
package/src/types/store.ts

* Superfluous generics removed from types like store, state etc. as they haven't really served a well-defined purpose on update

refactor(types)!: Remove generics from types except nodes, edges, elements

---

package/src/store/actions.ts
package/src/types/edge.ts

* Bind source and target nodes to graph edges for convenience

feat(edges): Add source/target nodes to graph edges

---

package/src/components/Nodes/NodeWrapper.vue
package/src/composables/useVueFlow.ts

* Allow user to pass refs to composable (will not trigger an automatic re-set of state when refs are changed)

refactor: Accept maybe refs as options for usevueflow

---

package/src/additional-components/Controls/Controls.vue
package/src/composables/useZoomPanHelper.ts
package/src/types/components.ts

* Allow user to pass refs to composable (will not trigger an automatic re-set of state when refs are changed)

fix(zoom): Use scaleBy instead of scaleTo for zoom

---

package/src/components/Edges/EdgeWrapper.vue
package/src/components/Handle/Handle.vue
package/src/components/Nodes/NodeWrapper.vue
package/src/components/NodesSelection/NodesSelection.vue
package/src/composables/useHandle.ts
package/src/composables/useVueFlow.ts
package/src/composables/useZoomPanHelper.ts
package/src/container/SelectionPane/SelectionPane.vue
package/src/container/Viewport/Transform.vue
package/src/container/Viewport/Viewport.vue
package/src/types/hooks.ts
package/src/types/store.ts

* For easier access (and shorter syntax) of event emitters add emits property to store
* Make hooks, emits and onEvent triggers readonly properties

feat: Add emits property to store

---

package/src/components/Nodes/NodeWrapper.vue
package/src/store/actions.ts
package/src/utils/changes.ts

* Only loop selected nodes instead of all nodes when determining position changes

refactor(nodes): minimize position change loops

---

.gitignore
packages/vue-flow/src/components/Nodes/NodeWrapper.vue
packages/vue-flow/src/container/Viewport/Viewport.vue
packages/vue-flow/src/store/getters.ts

* use `.find` instead of computed index

fix(nodes): `getNode` not returning proper node element

---

docs/.eslintrc.js
docs/components/home/Features.vue
docs/components/home/flows/Basic.vue
packages/vue-flow/src/types/edge.ts
packages/vue-flow/src/types/flow.ts
packages/vue-flow/src/types/node.ts

* Remove `BaseElement` type
* Merge base element props into `Node` and `Edge` types
* Allow `ClassFunc` and `StyleFunc` types to specify what element type is used in callback

refactor(nodes,edges): Remove `BaseElement` type

---

docs/components/examples/teleport/TeleportableNode.vue
docs/components/examples/teleport/useTransition.js
examples/vite/src/CustomNode/CustomNode.vue
packages/vue-flow/src/components/Nodes/NodeWrapper.vue
packages/vue-flow/src/container/VueFlow/VueFlow.vue
packages/vue-flow/src/store/actions.ts
packages/vue-flow/src/store/hooks.ts
packages/vue-flow/src/types/hooks.ts
packages/vue-flow/src/types/store.ts

* remove node element as prop from custom node components
* add `updateNodeInternals` action to force update node dimensions and position (i.e. transitions etc.)
* add `updateNodeInternals` hook to trigger update in nodes

refactor(nodes): add updateNodeInternals action

---

docs/src/guide/vue-flow/config.md
packages/vue-flow/src/container/VueFlow/VueFlow.vue
packages/vue-flow/src/container/VueFlow/watch.ts
packages/vue-flow/src/store/state.ts
packages/vue-flow/src/types/connection.ts
packages/vue-flow/src/types/flow.ts
packages/vue-flow/src/types/store.ts

* auto-connect allows to easily enable the default add edge change handler (shown in the examples)
* allow auto-connect to be a function that returns false when connection is cancelled or partial edge when it should be created

feat(vue-flow): add `autoConnect` option

---

docs/src/guide/theming.md
packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
packages/vue-flow/src/container/Viewport/Transform.vue
packages/vue-flow/src/style.css

* connection lines should be above nodes
* selected node should be above edges

feat(edges): move connection lines to separate container

---

packages/vue-flow/src/components/Nodes/NodeWrapper.vue

* connection lines should be above nodes
* selected node should be above edges

refactor(nodes): use `content-box` for resize observer

---

docs/components/examples/nested/App.vue
docs/src/guide/vue-flow/config.md
packages/vue-flow/src/components/Nodes/NodeWrapper.vue
packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
packages/vue-flow/src/container/VueFlow/VueFlow.vue
packages/vue-flow/src/store/state.ts
packages/vue-flow/src/types/flow.ts

* only group edges by z-index when `elevateEdgesOnSelect` is true
* add `elevateEdgesOnSelect` option

feat(edges): add `elevateEdgesOnSelect` prop

---

docs/src/guide/node.md
packages/vue-flow/src/components/Nodes/NodeWrapper.vue
packages/vue-flow/src/env.d.ts
packages/vue-flow/src/types/hooks.ts
packages/vue-flow/src/utils/node.ts

* add listener for `update-node-internals` on node component
* update internals when event is emitted

feat(nodes): allow node internals to be updated by event

---

docs/src/guide/vue-flow/config.md
packages/vue-flow/src/components/ConnectionLine/ConnectionLine.vue
packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
packages/vue-flow/src/container/EdgeRenderer/Marker.vue
packages/vue-flow/src/container/EdgeRenderer/MarkerDefinitions.vue
packages/vue-flow/src/store/state.ts
packages/vue-flow/src/types/connection.ts
packages/vue-flow/src/types/flow.ts
packages/vue-flow/src/types/store.ts

* allow defining markers on connection lines
* deprecate `connectionLineType`
* deprecate `connectionLineStyle`

feat(edges): add `connectionLineOptions` prop

---

packages/vue-flow/src/composables/useKeyPress.ts
packages/vue-flow/src/container/SelectionPane/SelectionPane.vue

* revert keypress listener on input elements (except button)
* skip keypress events on elements with `.nokey` classname

feat(viewpane): block keypress on inputs and `.nokey` elements

---

packages/vue-flow/src/components/Nodes/NodeWrapper.vue
packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
packages/vue-flow/src/container/VueFlow/watch.ts

* revert keypress listener on input elements (except button)
* skip keypress events on elements with `.nokey` classname

refactor: move watch flush timing to pre 

---

packages/vue-flow/src/components/Nodes/NodeWrapper.vue
packages/vue-flow/src/container/NodeRenderer/NodeRenderer.vue

* instead of computed getter use prop to pass node
* avoids error when node gets deleting from custom node with `removeNodes`
- Issue 1
- Issue 2
- ...
- ...

release: 0.4.37

---

docs/src/guide/edge.md
docs/src/guide/vue-flow/config.md
examples/vite/src/UpdatableEdge/UpdatableEdgeExample.vue
packages/vue-flow/src/components/Edges/Wrapper.ts
packages/vue-flow/src/container/EdgeRenderer/EdgeRenderer.vue
packages/vue-flow/src/types/edge.ts
packages/vue-flow/src/types/flow.ts
packages/vue-flow/src/types/store.ts

- Introduced new type EdgeUpdatable
- Updated edge wrapper to only draw markers based on updatable prop
- Updated typedocs and vite example
- Being able to choose if only source or target of an edge should be updatable
- Update more examples

Updatable edgelogic updated to enable either source or target marker

---

packages/vue-flow/src/utils/graph.ts

- Replace `getElementFromPoint` with `elementFromPoint`
- #280

fix: use `elementFromPoint`

---

packages/vue-flow/src/store/actions.ts
packages/vue-flow/src/types/changes.ts
packages/vue-flow/src/utils/drag.ts

- add `from` position (starting position of the node when drag starts) to node position change events
- can be used for position rollbacks

feat(nodes): add from position to position change event 

---

e2e/cypress/component/1-store/nodes/addSelectedNodes.cy.ts
packages/vue-flow/src/composables/useKeyPress.ts
packages/vue-flow/src/container/Viewport/Viewport.vue

* set `selectionKeyCode` to true, for figma style selection (selection without keypress)
- ...

feat(viewpane): support boolean keycode value

---

.changeset/violet-mugs-attend.md
packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
packages/core/src/store/getters.ts

- Fix edges not returned by getter when `paneReady` event is triggered

fix(edges): edges not returned by getter when `paneReady` event is triggered

---

.changeset/green-dragons-explain.md
e2e/cypress/component/2-vue-flow/connect.cy.ts
e2e/cypress/component/2-vue-flow/updateEdge.cy.ts
packages/core/src/composables/useHandle.ts
packages/core/src/store/actions.ts
packages/core/src/store/state.ts
packages/core/src/types/store.ts

- prevent `mouseup` handler resetting the click startHandle
- add click startHandle

fix(handles): connectOnClick reset before connections can be made

---

docs/src/guide/index.md

Removed 0.x.x. warning from docs

Removed 0.x.x. warning from docs

---

.changeset/stupid-bags-dance.md
packages/core/src/utils/graph.ts

- use `shallowRef` to wrap data and events objects

fix(core): use shallowReactive for node/edge data & events 

---

.changeset/fast-shoes-beam.md
.changeset/nice-lobsters-develop.md
packages/core/src/components/UserSelection/UserSelection.vue
packages/core/src/container/SelectionPane/SelectionPane.vue

- disable user selection when `elementsSelectable` is false
- prevent node selection box from appearing before mouseup event

fix(core): disable user selection if `elementsSelectable` is false 

---

.changeset/clever-taxis-work.md
packages/core/src/components/Nodes/NodeWrapper.vue
packages/core/src/container/NodeRenderer/NodeRenderer.vue
packages/core/src/container/VueFlow/VueFlow.vue
packages/core/src/store/hooks.ts
packages/core/src/types/hooks.ts

- emit `nodesInitialized` event when all nodes are mounted

feat(core,nodes): add nodesInitialized event hook

---

.changeset/sharp-gifts-doubt.md
packages/core/src/components/Edges/BaseEdge.ts
packages/core/src/components/Edges/BezierEdge.ts
packages/core/src/components/Edges/SimpleBezierEdge.ts
packages/core/src/components/Edges/SmoothStepEdge.ts
packages/core/src/components/Edges/StepEdge.ts
packages/core/src/components/Edges/StraightEdge.ts
packages/core/src/components/Edges/Wrapper.ts
packages/core/src/types/edge.ts
packages/core/src/utils/graph.ts

- add `interactionWidth` prop to edge
- add a second (invisible) edge path that increases pointer interactivity radius

feat(edges): add `interactionWidth` prop to edges

---

.changeset/thick-pots-accept.md
packages/core/src/components/ConnectionLine/ConnectionLine.vue
packages/core/src/components/Edges/utils/bezier.ts
packages/core/src/components/Edges/utils/smoothstep.ts

fix(core,edges): when connection mode is `Loose` use all handles as connection line source handle

---

.changeset/pretty-cows-worry.md
packages/core/src/container/Viewport/Viewport.vue

- for better visibility, switch drag hand to crosshair while connecting

fix(core): improper check for selection key code in zoom-pan filter 

---

.changeset/rude-tables-cry.md
packages/additional-components/src/minimap/MiniMap.vue
packages/additional-components/src/minimap/types.ts
packages/core/src/theme-default.css

- To easily style a border + border width on the minimap mask

feat(additional-components): add `maskStrokeColor` and `maskStrokeWidth` props to MiniMap

---

.changeset/sixty-stingrays-glow.md
.changeset/wise-plums-shop.md
packages/core/src/store/actions.ts
packages/core/src/store/state.ts
packages/core/src/types/flow.ts

- Change 1
- Change 2
- ...
- ...

feat(core): add __experimentalFeatures flag to store

---

.changeset/swift-buses-argue.md
packages/core/src/utils/watch.ts

fix(core): update model-value regardless of arr length

---

.changeset/plenty-turkeys-remain.md
packages/core/src/utils/graph.ts

- Replace `shallowReactive` with `reactive` in nested node/edge properties

refactor(core): change `shallowReactive` properties in elements to `reactive`

---

.changeset/empty-candles-wash.md
packages/core/package.json
packages/core/patch/slots.js

- Patch slot types after build

fix(core): patch VueFlow slots after build and apply correct types

---

.changeset/old-chefs-float.md
packages/core/src/store/actions.ts
packages/core/src/utils/graph.ts
packages/core/src/utils/store.ts

- Make node and edge objects deeply reactive
- mark non-reactive properties (like event object) as raw
- Separate model and store watchers from each other

refactor(core,nodes,edges): deep reactive nodes and edges

---

.changeset/purple-mice-cry.md
packages/core/src/components/Handle/Handle.vue

- If defined, use connectable prop, otherwise fall back to global connectable value

fix(core): use connectable prop or global connectable in Handle

---

.changeset/metal-spies-provide.md
.changeset/sweet-hotels-grin.md
packages/core/src/store/getters.ts
packages/core/src/types/connection.ts
packages/core/src/types/store.ts

- add `getNodesInitialized` getter to store
- make `sourceHandle` and `targetHandle` optional in `Connection` type

feat(core): add getNodesInitialized getter to store

---

.changeset/dirty-ants-divide.md
.changeset/violet-squids-peel.md
packages/core/src/container/VueFlow/VueFlow.vue
packages/core/src/utils/watch.ts

- Change 1
- Change 2
- ...
- ...

fix(core): only trigger store watcher immediately when els were set

---

.changeset/eleven-dryers-applaud.md
packages/core/package.json
packages/core/patch/slots.js

- Slots patch regression due to changed import names

fix(core): use regexp to fetch imports in slots patch

---

packages/core/src/components/UserSelection/UserSelection.vue
packages/core/src/utils/a11y.ts

- Change 1
- Change 2
- ...
- ...

fix(a11y): use correct vue flow aria names

---

.changeset/dry-ligers-do.md
packages/core/src/store/actions.ts
packages/core/src/types/edge.ts
packages/core/src/types/node.ts
packages/core/src/utils/graph.ts

- add `deletable` option to nodes and edges
- prevent elements that have `deletable` set to false from being removed by `removeNodes` or `removeEdges`

feat(core): add deletable option to nodes and edges

---

.changeset/metal-ties-agree.md
packages/core/src/composables/useZoomPanHelper.ts

fix(core): exclude hidden nodes in fitView when includeHiddenNodes is false

---

.changeset/few-walls-search.md
packages/core/src/components/Edges/EdgeWrapper.ts

fix(core): avoid triggering edge update when mouse btn is not left

---

.changeset/fresh-seas-admire.md
packages/core/src/store/actions.ts

refactor(core): fit view initially when node dimensions are updated

---

.changeset/funny-turkeys-give.md
packages/core/src/store/actions.ts
packages/core/src/types/store.ts
packages/core/src/utils/store.ts

feat(core): add option to avoid replacing edge id when updating

---

.changeset/clever-countries-hammer.md
packages/core/src/utils/graph.ts

- Use `Object.assign` when parsing node to avoid mutating original object

fix(core,nodes): use object assign to parse node 

---

packages/core/src/container/EdgeRenderer/EdgeRenderer.vue

In https://github.com/bcakmakoglu/vue-flow/commit/c62c18a20d72db1591b69ba8e2cd3fdd7872af9b#diff-67a7ade8d1cb21ddf3888d44a38161a4aa06bebaf0ef24ac97387e4d67eb61f9L51, a usage of `watch` was removed. This usage of `watch` stored the unwatch function in a local variable called `stop`, which was called in `onBeforeUnmount()`. However, the removal of this `onBeforeUnmount` was missed, causing the `stop` call to start referring to [`window.stop`](https://developer.mozilla.org/en-US/docs/Web/API/Window/stop) (which I had no idea existed before today). 
The end result is that unmounting a `VueFlow` component causes all in-flight network requests to be immediately aborted.

fix(core): remove erroneous window.stop in EdgeRenderer

---

.changeset/rare-walls-wash.md
packages/background/src/Background.vue
packages/core/src/composables/useKeyPress.ts
packages/core/src/utils/graph.ts

fix(core): correct return type of getIncomers & getOutgoers

---

.changeset/metal-parrots-allow.md
packages/core/src/store/actions.ts

- Reset node and edge state before resetting the rest of the state

fix(core): reset nodes and edges before state

---

.changeset/bright-hornets-sell.md
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/composables/useDrag.ts

- Cleanup reactivity transform
- Cleanup unnecessary refs
- fetch node obj in drag handler to avoid possibly fetching outdated node obj (if it's been overwritten)

refactor(core): pass drag handle to useDrag

---

packages/node-resizer/src/NodeResizer.vue

Hi! First of all, thank you for your efforts, the library makes a lot of things easier for us!

fix(node-resizer): Use correct class name and style for handle controls

---

.changeset/nervous-dots-tickle.md
packages/core/src/composables/useViewport.ts
packages/core/src/composables/useVueFlow.ts
packages/core/src/container/Viewport/Transform.vue
packages/core/src/store/actions.ts

fix(core): use noop viewport operations instead of waiting for promise

---

.changeset/dry-boxes-raise.md
examples/vite/src/Basic/BasicOptionsAPI.vue
packages/core/src/composables/useViewport.ts
packages/core/src/composables/useZoomPanHelper.ts
packages/core/src/types/zoom.ts

- Return promises from viewport actions, which are resolved when the viewport transitions end

feat(core): resolve promise from viewport actions on transition end

---

.changeset/mean-peaches-develop.md
.changeset/soft-icons-marry.md
packages/core/src/store/actions.ts
packages/core/src/types/store.ts
packages/core/src/utils/graph.ts

- Allow passing `string` | `Node` | `{ id }` to `getIncomers` / `getOutgoers` utils
- Add `removeChildren` arg to `removeNodes`
- Allows recursively removing child nodes of a parent

feat(core): add flag to removeNodes to remove children of a node

---

.changeset/lemon-badgers-report.md
packages/node-resizer/src/NodeResizer.vue

fix(node-resizer): wait for node to be initialised before enforcing min/max size

---

docs/components/home/Showcase.vue

Currently the showcase section of the homepage uses octai.com as the URL for both Octai and Kestra's showcase sections. This PR just updates it to use the correct URL.
- Change Kestra's showcase section to point to the correct URL.

docs: fix kestra showcase link

---

.changeset/twenty-pears-act.md
packages/core/src/container/Viewport/Viewport.vue

- When `panActivationKeyCode` is triggered, enable panning by dragging

fix(core): allow pan on drag when pan key is activated

---

.changeset/neat-pumpkins-yawn.md
.changeset/seven-walls-argue.md
packages/core/src/composables/useWatchProps.ts
packages/core/src/store/actions.ts

- Add immediate flag to prop watchers so we properly assign initial prop values to the store state
- Remove waiting for d3zoom to be available before setting min/max zoom etc. as these values should be available when d3zoom is initialized making waiting redundant here and causing multiple calls of `setState` to queue the execution of this watcher

fix(core): add immediate flag to prop watchers

---

.changeset/pink-hotels-laugh.md
packages/core/src/store/actions.ts

- When checking for intersections use the resulting nodeRect and not the passed nodeOrRect

fix(core): use node rect for intersection check

---

.changeset/nasty-planes-prove.md
packages/core/src/container/Viewport/Viewport.vue

- Allow zooming when zoom key is pressed and user hovers a nopan element

fix(core): respect zoom key when hovering nopan elements

---

packages/pathfinding-edge/README.md

- Deprecate pathfinding pkg, will be removed with next major release
- Hasn't been maintained for a long time
- No usage requests

refactor(pathfinding-edge): deprecate pkg

---

packages/core/src/components/Nodes/NodeWrapper.ts

- Use `getConnectedEdges` from `useVueFlow` in node wrapper

chore(core): cleanup node wrapper

---

.changeset/tall-ligers-tan.md
packages/core/src/components/Edges/EdgeLabelRenderer.vue
packages/pathfinding-edge/README.md

- Use nullish check when looking up the edge label renderer el to avoid potential calls of `getElementsByClassname` on `null`

fix(core): use nullish check when finding edge label renderer el

---

.changeset/shiny-sloths-applaud.md
.changeset/small-steaks-accept.md
.changeset/wise-apes-enjoy.md
docs/.gitignore
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/store/actions.ts
packages/core/src/store/state.ts
packages/core/src/types/store.ts
packages/node-resizer/src/NodeResizer.vue
packages/pathfinding-edge/README.md

- Pass the correct node id to the resize control component

fix(node-resizer): pass correct node id to resize control

---

packages/core/src/store/actions.ts
packages/core/src/types/changes.ts
packages/core/src/utils/changes.ts

First, thank you for this awesome library, we love it and use it for one of our most important parts of our apps.
This PR adds the `sourceHandle` and `targetHandle` if available on the edge removal entry.
Back in 1.21 you were able to look up the edge being removed before it actually got removed. Now after the upgrade you cannot do that as the edge is already removed so there is no way to know which handles were involved with that edge.
Also it feels arbitrary/harmless to include the handle ids since it is information readily available to all code paths creating the removal entry item.
In our complex flow builder, a node can have multiple outgoing edges originating from multiple handles. We were relying on the handle ids to differentiate between the different outgoing edges as the edge id …

feat(core): add source and target handle ids to edge removal change

---

packages/core/src/style.css

- Fix the issue of pushing out the panel when copying a large amount of text to the textarea
https://github.com/bcakmakoglu/vue-flow/assets/14084550/3611da11-63ee-4e59-a14f-4a58fc0e2d7f

fix(core): use `overflow: clip` for viewport element

---

.changeset/khaki-worms-hug.md
packages/core/src/components/Handle/Handle.vue

- Expose `handleClick` `handlePointerdown` `onClick` and `onPointerDown` functions of handle components

feat(core,handle): expose handler functions

---

.changeset/beige-trees-design.md
packages/core/src/components/ConnectionLine/index.ts

- Pass vue flow instance id to `getMarkerId` in connection line component

fix(core,connection-line): pass flow id to `getMarkerId`

---

.changeset/brown-garlics-sin.md
packages/core/src/composables/useKeyPress.ts

- Check if `event.code` or `event.key` are defined before trying to match keyfilter against keys

fix(core,key-press): check if key or code exists before matching

---

.changeset/tame-lions-relate.md
packages/core/src/utils/graph.ts

- Instead of checking for truthiness of values, check if values are numeric in `isRect`

fix(core,utils): check if values are numeric in isRect

---

packages/core/src/composables/useResizeHandler.ts

- use `onMounted` & `onBeforeUnmount` in `useResizeHandler` instead of `watchEffect`

refactor(core,viewport): replace watchEffect with onMounted/onBeforeUnmount

---

.changeset/chilly-cameras-promise.md
.changeset/empty-moose-report.md
.changeset/giant-pants-speak.md
packages/core/src/composables/useHandleConnections.ts
packages/core/src/index.ts
packages/core/src/store/actions.ts
packages/core/src/store/state.ts
packages/core/src/types/store.ts
packages/core/src/utils/store.ts

- Add `connectionLookup` to state
- Maps handles to connections (edges) for quick lookups
- Add `useHandleConnections` composable
- Returns a `ComputedRef<Connection[]>` based on the handle parameters passed into the composable
```ts
const connections = useHandleConnections({
// type of the handle you are looking for - accepts a `MaybeRefOrGetter<string>`
type: 'source',
// the id of the handle you are looking for - accepts a `MaybeRefOrGetter<string | undefined> | undefined` [OPTIONAL]
id: 'a',
// if not provided, the node id from the NodeIdContext is used - accepts a `MaybeRefOrGetter<string | undefined> | undefined`
nodeId: '1',
// a cb that is called when a new connection is added
onConnect: (params) => {
console.log('onConnect', params)
},
// a cb that is called when a connection is …
```

feat(core,composables): add useHandleConnections composable

---

.changeset/fresh-avocados-clap.md
packages/core/src/utils/edge.ts

- Avoid falling back to first handle if handle length === 1
- Search for handle by id if a handle id was passed

refactor(core): find handle by id regardless of num of handles

---

.changeset/curvy-spies-approve.md
.changeset/slimy-cameras-pull.md
packages/core/src/store/actions.ts
packages/core/src/types/edge.ts
packages/core/src/types/node.ts

- Omit `events` property from nodes and edges returned by `toObject`

refactor(core): omit events when calling toObject

---

.changeset/gorgeous-rules-relate.md
packages/core/src/composables/useOnInitHandler.ts
packages/core/src/composables/useViewport.ts
packages/core/src/composables/useVueFlow.ts
packages/core/src/container/VueFlow/VueFlow.vue
packages/core/src/store/actions.ts
packages/core/src/store/hooks.ts
packages/core/src/store/state.ts
packages/core/src/types/flow.ts
packages/core/src/types/hooks.ts
packages/core/src/types/store.ts
tests/cypress/support/component.ts

- add `onInit` hook
- deprecate `onPaneReady`
- add `useOnInitHandler`
- emit pane ready from new composable
- add `viewportInitialized` state var

 refactor(core): use useOnInitHandler to emit paneReady event

---

.changeset/cuddly-flies-change.md
.changeset/nice-suits-pull.md
packages/core/src/store/actions.ts
packages/core/src/types/store.ts
tests/cypress/component/1-store/nodes/updateNode.cy.ts
tests/cypress/component/1-store/nodes/updateNodeData.cy.ts

- Add `updateNodeData` action
- Add `updateNode` action
```ts
const { updateNode } = useVueFlow()
updateNode('1', { position: { x: 100, y: 100 } })
```
```ts
const { updateNodeData } = useVueFlow()
updateNodeData('1', { foo: 'bar' })
```

feat(core): add updateNode & updateNodeData actions to store

---

.changeset/spotty-buckets-suffer.md
packages/core/src/components/Nodes/NodeWrapper.ts

- When source/target handle position of a node changes, update it's dimensions on next tick

fix(core): update node dimensions on next tick

---

.changeset/old-jokes-raise.md
packages/core/src/composables/useHandleConnections.ts
packages/core/src/composables/useNodesData.ts
packages/core/src/index.ts
tests/cypress/component/4-composables/useNodesData.cy.ts

- Add `useNodesData` composable
```ts
const nodeId = '1'
const data = useNodesData(nodeId)
console.log(data.value) // '[{ /* ... */ }]
```
```ts
const nodeIds = ['1', '2', '3']
const data = useNodesData(nodeIds)
console.log(data.value) // '[{ /* ... */ }]
```
```ts
import type { Node } from '@vue-flow/core'
interface Data {
foo: string;
bar: string;
}
type MyNode = Node<CustomNodeData>
const nodeId = '1'
const data = useNodesData([nodeId], (node): node is MyNode => {
return 'foo' in node.data && 'bar' in node.data
})
console.log(data.value) // '[{ /* foo: string; bar: string */ }]
```

feat(core,composables): add `useNodesData`

---

.changeset/curvy-needles-enjoy.md
packages/core/src/container/NodeRenderer/NodeRenderer.vue

- Call `onNodesInitialized` whenever `areNodesInitialized` is `true` instead of calling it only once

refactor(core): call nodes initialized whenever areNodesInitialized is true

---

.changeset/odd-months-clap.md
packages/core/src/composables/useVueFlow.ts
packages/core/src/store/actions.ts
packages/core/src/store/state.ts
packages/core/src/utils/graph.ts
packages/core/src/utils/store.ts

- Use existing node / edge objects for target of `Object.assign` when parsing nodes / edges

fix(core): use existing node/edge obj for assignment

---

.changeset/sour-swans-fail.md
.changeset/tame-gifts-reply.md
docs/src/.vitepress/config.mts
docs/src/guide/troubleshooting.md
packages/core/src/index.ts
packages/core/src/utils/errors.ts

- Add error args to `VueFlowError`
- Export `isErrorOfType` to narrow the args type

feat(core,error): add error args to err

---

packages/core/src/components/Nodes/DefaultNode.ts
packages/core/src/components/Nodes/InputNode.ts
packages/core/src/components/Nodes/OutputNode.ts

- Use data object for default node labels since `node.label` is deprecated now

refactor(core): use `data` obj for labels in default nodes

---

.changeset/sour-crews-boil.md
packages/background/src/Background.vue
packages/background/src/types.ts

- Deprecate `bgColor` prop
- Deprecate `patternColor` prop (replaced by just `color` prop)
- Deprecate `BackgroundVariants` enum

refactor(background): deprecate bgcolor prop

---

packages/core/src/composables/useNodesInitialized.ts
packages/core/src/index.ts
packages/core/src/store/getters.ts
packages/core/src/types/store.ts
tests/cypress/component/4-composables/useNodesInitialized.cy.ts

- Add `useNodesInitialized` composable
- Deprecate getters for nodes initialized

feat(core,composables): add `useNodesInitialized` composable

---

docs/src/guide/node.md

- Update `sourceHandle` => `sourcePosition`
- Update `targetHandle` => `targetPosition`
Incorrect prop names in documentation

fix(docs): correct prop names for node guide

---

.changeset/silent-pigs-swim.md
packages/core/src/components/Edges/EdgeWrapper.ts
packages/core/src/components/Nodes/NodeWrapper.ts

- Avoid catching esc key press if keyboard a11y is disabled

fix(core): prevent esc keypress when a11y is disabled

---

.changeset/selfish-doors-buy.md
packages/core/src/composables/useNodesData.ts
tests/cypress/component/4-composables/useNodesData.cy.ts

- Add `type` and `id` to return of `useNodesData`

feat(core,composables): add type and id to useNodesData

---

.changeset/eleven-bulldogs-rhyme.md
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/style.css

fix(core): use default cursor and apply drag cursor if node is draggable

---

.changeset/tall-years-roll.md
packages/core/src/types/edge.ts

- Remove invalid `ref` prop from `BaseEdge` component

fix(core): remove ref prop from BaseEdge

---

.changeset/purple-tomatoes-repair.md
packages/core/src/components/Edges/utils/smoothstep.ts

fix(core,edges): use nullish check to fallback to default center

---

.changeset/shaggy-birds-share.md
packages/core/src/composables/useNodesInitialized.ts
packages/core/src/utils/graph.ts

fix(core): check if dimensions exist in useNodesInitialized

---

.changeset/chilly-cameras-smile.md
packages/core/src/types/flow.ts

fix(core,types): use separate interfaces for node/edge events

---

docs/src/guide/vue-flow/config.md

docs: replace `source.id` with `source`

---

.changeset/lovely-buttons-tickle.md
packages/core/src/container/Viewport/Viewport.vue

- Allow wheel events to bubble up to the user if the event is unused and not caught by the viewport

fix(core): allow wheel evt to bubble up if not used by vf 

---

.changeset/fresh-wolves-melt.md
packages/core/src/composables/useStylesLoadedWarning.ts
packages/core/src/container/VueFlow/VueFlow.vue
packages/core/src/utils/errors.ts
packages/core/src/utils/log.ts

- Add warning when style imports are missing

feat(core): add missing styles warning

---

.changeset/curly-phones-reply.md
.changeset/six-trainers-juggle.md
packages/controls/src/types.ts
packages/core/src/types/panel.ts
packages/minimap/src/types.ts

- Export `PanelPositionType` from core pkg
- Allow `PanelPositionType` as position in minimap and controls cmp

feat(core): export PanelPositionType

---

.changeset/silver-cycles-mix.md
packages/core/src/composables/useHandleConnections.ts

- Use separate prevConnections map to ensure comparison check is correct and callbacks are executed

fix(core): use separate prevConnections map

---

packages/minimap/src/MiniMap.vue
packages/minimap/src/types.ts

- Added the optional option for a mask border radius on the minimap
- - Default is still 0 as before.

feat(minimap): add `maskBorderRadius` prop

---

.changeset/short-eels-turn.md
packages/core/src/composables/useHandleConnections.ts
packages/core/src/types/connection.ts
packages/core/src/types/store.ts
packages/core/src/utils/store.ts

- Add `edgeId` to handle connections objects returned by `useHandleConnections`

feat(core): add edge id to handle connections

---

.changeset/large-kangaroos-wave.md
docs/examples/connection-radius/SnappableConnectionLine.vue
examples/vite/src/SnapHandle/SnappableConnectionLine.vue
packages/core/src/components/ConnectionLine/index.ts
packages/core/src/components/Handle/Handle.vue
tests/cypress/component/1-store/edges/connection.cy.ts
tests/cypress/component/2-vue-flow/connect.cy.ts
tests/cypress/component/2-vue-flow/customConnectionLine.cy.ts
tests/cypress/component/2-vue-flow/isValidConnection.cy.ts

- Remove auto generated handle id
- Use `null` as default handle id

refactor(core,handle): remove auto-generated handle ids

---

.changeset/warm-seahorses-retire.md
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/container/NodeRenderer/NodeRenderer.vue

- Use all nodes (even hidden ones) to render list of nodes
- Render `null` if node is hidden
- Re-observe  node element when visible

refactor(core): use all nodes in node renderer

---

.changeset/itchy-cats-kiss.md
.changeset/shaggy-feet-shout.md
packages/core/src/components/Edges/EdgeWrapper.ts
packages/core/src/container/NodeRenderer/NodeRenderer.vue
packages/core/src/store/getters.ts

- Render `null` if edge is hidden
- Remove hidden check from `getNodes` and `getEdges`

refactor(core): render null if edge is hidden

---

.changeset/selfish-vans-report.md
packages/core/src/composables/useDrag.ts

- Disable dragging when using multi-touch (like pinch zoom)

fix(core): disable drag when using multi-touch

---

.changeset/calm-pigs-yawn.md
.changeset/four-singers-suffer.md
packages/core/src/components/Edges/EdgeWrapper.ts
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/composables/useEdge.ts
packages/core/src/container/EdgeRenderer/EdgeRenderer.vue
packages/core/src/container/NodeRenderer/NodeRenderer.vue

- Only use node/edge id as dependency to re-render lists

refactor(core): use node/edge id as only dependency for nodes/edges list

---

.changeset/shy-kings-compare.md
packages/core/src/store/actions.ts
packages/core/src/store/getters.ts
packages/core/src/types/store.ts
packages/core/src/utils/storage.ts

- Replace internal nodeIds/edgeIds array with nodeLookup/edgeLookup maps

refactor(core): use node lookup map internally

---

.changeset/red-avocados-know.md
packages/core/src/composables/useVueFlow.ts
packages/core/src/composables/useWatchProps.ts
packages/core/src/container/VueFlow/VueFlow.vue
packages/core/src/utils/errors.ts

- Add overloads to `useVueFlow` 
- Allows using `useVueFlow(someId)` instead of passing an options obj
- Deprecation error for using the options obj

refactor(core): add overloads to useVueFlow

---

.changeset/thin-beans-wait.md
.changeset/thirty-days-retire.md
packages/core/src/types/edge.ts
packages/core/src/types/node.ts

- Allow passing `string[]` or `Record<string, any>` as class to node/edge objects

feat(core): allow string array or object as class to node/edge objects

---

.changeset/two-countries-brake.md
packages/core/src/composables/useDrag.ts

- When node drag ends and the threshold was not exceeded (meaning `dragStarted` is `false`) emit the node click event

fix(core): emit node click event when drag was ended with no movement

---

.changeset/giant-pears-agree.md
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/composables/useDrag.ts

- Check if node drag was aborted before trying to emit node click event

fix(core): emit node click if drag was aborted

---

.changeset/popular-cars-design.md
packages/core/src/composables/useDrag.ts

- ignore minor movements when marking a node drag as aborted

fix(core): ignore minor drag movements when marking aborted drag

---

packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/composables/useDrag.ts

- Dispatch click event if node drag was attempted but threshold was not exceeded

fix(core): dispatch click if drag move was attempted

---

.changeset/seven-ads-wait.md
docs/src/guide/vue-flow/config.md
packages/core/package.json
packages/core/src/index.ts
packages/minimap/package.json
packages/minimap/src/MiniMap.vue
packages/node-toolbar/package.json
packages/node-toolbar/src/NodeToolbar.vue
pnpm-lock.yaml

- Replace d3 with minimap instance of xyflow system

refactor(minimap)!: use xy minimap instance

---

.changeset/beige-shoes-fold.md
.changeset/funny-jokes-lie.md
packages/core/src/composables/useVueFlow.ts

- Prefer options id over scoped id when finding vue flow state
- Check if injected vue flow state id matches options or scope id, otherwise create new state

fix(core): check if injected state matches options and scope id 

---

.changeset/fluffy-mayflies-fetch.md
packages/core/src/store/actions.ts

- Push into dimensions changes array instead of adding by index

 fix(core): push into changes arr instead of using index 

---

.changeset/long-walls-join.md
packages/core/src/types/flow.ts

- Inline event names as unions to prevent Vue warning about non defined event names

 fix(core): inline event names 

---

.changeset/nice-seals-tickle.md
packages/core/package.json
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/utils/changes.ts

- Avoid overwriting size in styles object with node.width/height if size already exists in the styles object

 fix(core): prevent overwriting size in node styles object 

---

.changeset/swift-cups-pay.md
packages/core/src/composables/useDrag.ts

- Prevent drag-click handler when multi selection is active
- Cleanup drag-click condition to only be valid when a node has not been moved

 fix(core): prevent drag click when multi selection is active

---

.changeset/twelve-rules-exist.md
packages/core/src/components/Edges/EdgeWrapper.ts
packages/core/src/components/Nodes/NodeWrapper.ts

- Allow node/edge pointer events if a mouse event listener exists

fix(core,nodes,edges): allow pointer events if mouse evt listeners exist

---

docs/examples/connection-radius/SnappableConnectionLine.vue

Typo in documentation for [Connection Radius](https://vueflow.dev/examples/edges/connection-radius.html) `targetPosition` prop.

fix(docs): typo in SnappableConnectionLine.vue

---

.changeset/empty-falcons-obey.md
.changeset/nasty-panthers-admire.md
packages/core/src/composables/useKeyPress.ts
packages/core/src/container/Viewport/Viewport.vue
packages/core/src/style.css
packages/core/src/types/flow.ts
packages/core/src/types/store.ts

fix(core): allow pan on drag for non left-btn when selectionKeyCode is `true`

---

.changeset/lovely-hairs-push.md
packages/core/src/composables/useKeyPress.ts

- set `isPressed` to `true` on `blur` and `contextmenu` events if permant keypress is enabled

fix(core): set `isPressed` to `true` on `blur` and `contextmenu` events if permant keypress is enabled

---

.changeset/early-walls-attack.md
packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/composables/useDrag.ts
packages/core/src/composables/useGetPointerPosition.ts
packages/core/src/utils/general.ts
packages/core/src/utils/graph.ts

 fix(core): check if dragEnd event is UseDrag or MouseTouch event

---

.changeset/clever-eyes-leave.md
packages/core/src/components/Nodes/NodeWrapper.ts

fix(frontend,core): prevent scrolling when using arrow keys to move nodes

---

.changeset/chatty-ducks-invite.md
packages/core/src/store/actions.ts
packages/core/src/utils/store.ts

fix(core): update source/target node of updated edge

---

docs/examples/edge-markers/App.vue
docs/examples/edge-markers/CustomEdge.vue
docs/examples/edge-markers/CustomMarker.vue
docs/examples/edge-markers/index.ts
docs/examples/edge-markers/style.css
docs/examples/index.ts
docs/src/.vitepress/config.mts
docs/src/examples/edges/markers.md

- Add edge markers example to docs
- Demonstrates built-in, as well as custom markers

docs(examples): add edge markers example

---

.github/actions/install-dependencies/action.yaml
.github/workflows/build-and-test.yml
examples/vite/src/EasyConnect/EasyConnect.vue
examples/vite/src/EasyConnect/FloatingConnectionLine.vue
examples/vite/src/EasyConnect/FloatingEdge.vue
packages/core/src/components/ConnectionLine/index.ts
packages/core/src/components/Edges/EdgeWrapper.ts
packages/core/src/components/Handle/Handle.vue
packages/core/src/composables/useHandle.ts
packages/core/src/store/actions.ts
packages/core/src/types/handle.ts
packages/core/src/utils/edge.ts
packages/core/src/utils/handle.ts
packages/core/src/utils/node.ts
tests/cypress/component/2-vue-flow/updateEdge.cy.ts
tests/package.json

- Calculate handle positions with centered position
- Remove handleId check if handle has no id

 fix(core): use center position of handle as snapping point for connection lines

---

.changeset/three-phones-grow.md
packages/minimap/src/MiniMap.vue
packages/minimap/src/MiniMapNode.vue
packages/minimap/src/types.ts

fix(minimap): hide minimap node if graph node is hidden 

---

.changeset/stale-radios-listen.md
packages/core/src/components/Edges/BaseEdge.vue
packages/core/src/types/edge.ts

- Inherit attributes on main edge path element in BaseEdge component

refactor(core): inherit attrs on edge path el in `BaseEdge`

---

.changeset/tough-taxis-tan.md
packages/minimap/src/MiniMapNode.vue

- do not inherit attrs on minimap nodes
- bind attrs to minimap node elements

fix(minimap): bind attrs to minimap node 

---

.changeset/olive-fishes-fetch.md
packages/node-toolbar/src/NodeToolbar.vue

fix(node-toolbar): set default value for isVisible to undefined

---

.changeset/smooth-pillows-laugh.md
packages/core/src/store/actions.ts

- Defer update of connection lookup to prevent mismatch with edgelookup computation

fix(core): defer connection lookup

---

.changeset/old-moose-fly.md
packages/core/src/composables/useDrag.ts

fix(core): reset drag items on drag end

---

.changeset/thick-owls-double.md
packages/minimap/src/MiniMap.vue

- Filter hidden nodes from bounds of minimap

fix(minimap): filter hidden nodes from bounds

---

.changeset/lemon-terms-joke.md
packages/core/src/composables/useKeyPress.ts

- Prevent keypress events from being swallowed when btn element is focused

fix(core): add button to elements to ignore in useKeyPress

---

docs/src/guide/getting-started.md

- Fix the incorrect Mustache syntax in the example

docs: correct template syntax

---

.changeset/nine-bees-pay.md
packages/core/src/container/EdgeRenderer/MarkerDefinitions.vue

fix(core): add aria hidden to markers

---

.changeset/blue-frogs-swim.md
packages/core/src/composables/useKeyPress.ts

- Set default for `actInsideInputWithModifier` to `true`
- Allow multi select when input is focused

fix(core): allow multiselect when input is focused

---

packages/core/src/components/Nodes/NodeWrapper.ts
packages/core/src/store/state.ts
packages/core/src/types/flow.ts
packages/core/src/types/node.ts

Added the possibility to customize HTML attributes of `.vue-flow__node` elements, globally through the nodesAttributes prop, and for each single node.
None
None
For my use case, I need greater flexibility in customizing ARIA attributes — for example, being able to explicitly set a `role` or provide additional `aria-*` properties.
Currently, `role="button"` is set automatically when focusable is true and omitted otherwise, with no way to override this behavior. While `aria-label` can be configured, this alone is often not sufficient for proper accessibility. Other attributes, such as aria-describedby, are managed internally and cannot be customized externally, which limits the ability to implement more advanced accessibility patterns.
According to …

feat(core): add dom attributes option for nodes
